# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestTokoin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestTokoin
	pod 'Alamofire', '~> 5.2'
	pod 'SVProgressHUD'
 	pod 'Kingfisher', '~> 5.0'

  target 'TestTokoinTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Alamofire', '~> 5.2'
	pod 'SVProgressHUD'
 	pod 'Kingfisher', '~> 5.0'
  end

end
